---
title: "analysis"
output: html_document
date: "2024-10-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load libraries
library(tidyverse)

# Load mtcars dataset
data(mtcars)

# Basic summary of the dataset
summary(mtcars)

create_scatter_plot <- function(df) {
  ggplot(df, aes(x = hp, y = mpg, color = factor(cyl), size = wt)) +
    geom_point() +
    theme_minimal() +
    labs(title = "Miles Per Gallon vs Horsepower",
         x = "Horsepower",
         y = "Miles Per Gallon",
         color = "Cylinders",
         size = "Weight")
}

# Call the function
create_scatter_plot(mtcars)


# Linear model predicting mpg based on hp
model <- lm(mpg ~ hp, data = mtcars)
summary(model)

```
```{r}
# Bar plot of the number of cylinders
ggplot(mtcars, aes(x = factor(cyl))) +
  geom_bar() +
  labs(title = "Count of Cars by Cylinder",
       x = "Cylinders",
       y = "Count")
```
```{r}
# Linear model predicting mpg based on hp and wt
model2 <- lm(mpg ~ hp + wt, data = mtcars)
summary(model2)
```


```{r}
# Boxplot comparing mpg by transmission type
ggplot(mtcars, aes(x = factor(am), y = mpg)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Comparison of MPG by Transmission Type",
       x = "Transmission (0 = automatic, 1 = manual)",
       y = "Miles Per Gallon")
```

